### ISSUE TITLE
[FirstKeyBoardEngine] addWord메서드 기능 구현

### ISSUE THREAD

**Issue by kirkim** [iclxxud/ios-wanted-CustomKeyboard#39]
# 작업목록
- [x] 기본Tool 메서드: 1.유니코드를 분리, 2.결합, 3.Int->String, 4.String->Int 메서드
- [x] 받침 + 입력값의 경우 처리하는 메서드
- [x] 받침x + 입력값의 경우 처리하는 메서드
- [x] 자음 + 입력값의 경우 처리하는 메서드
- [x] 모음 + 입력값의 경우 처리하는 메서드

**Comment by kirkim** [comment]
ㄴhttps://github.com/iclxxud/ios-wanted-CustomKeyboard/commit/082ce8f13dcb6c15f28f9a6b60ea62e6c96fba21 
받침코드로 된 변수를 초성코드로 변환시키는 메서드를 Support타입에 추가해줘서 버그를 수정해 줬습니다.

**Comment by iclxxud** [comment]
이해 완료!
