### ISSUE TITLE
[FirstKeyBoardEngine] removeWord메서드 기능 구현

### ISSUE THREAD

**Issue by kirkim** [iclxxud/ios-wanted-CustomKeyboard#40]
# 작업목록
- [x] 받침 + 입력값의 경우 처리하는 메서드
- [x] 받침x + 입력값의 경우 처리하는 메서드
- [x] 자음 + 입력값의 경우 처리하는 메서드
- [x] 모음 + 입력값의 경우 처리하는 메서드

**Comment by iclxxud** [comment]
이해 완료!
